### PR TITLE
add SortableApi

### PR DESCRIPTION
**Pull request by jonhoman**
@darbyfrey @ywong19 @fgv02009 

The SubCategories API in business-service uses this module. Porting from
napa.

A few things to consider:
- Do we want the `SortableApi` in napa_rails? We could also copy the `sort_from_params` method directly into the SubCategories API. But, the LoyaltyUsers API in user-facts-service also needs `sort_from_params`.
- The specs uses the acts_as_fu gem to create fake AR models. Are we okay with adding that development dependency? 
- I specified the AR dependency as earlier than AR 5.0, since all of our services are using AR pre-5.0. I think that makes sense...

### CODE REVIEW

**Comment by darbyfrey** [comment]
This seems fine to me. Couple questions:
1. Do we need to set the Rails version dependency? Does it matter?
2. I'm fine with `acts_as_fu` it's only for the test environment, right?

**Comment by jonhoman** [comment]
> 1. Do we need to set the Rails version dependency? Does it matter?

Setting AR prior to 5.0 will enforce that Rails is also prior to 5.0. 

> 1. I'm fine with acts_as_fu it's only for the test environment, right?

Correct.

I still need to figure out why the build is failing. I've gotten further:

```
bundle exec rspec --format documentation --color spec
bundler: failed to load command: rspec (/home/ubuntu/napa_rails/vendor/bundle/ruby/1.9.1/bin/rspec)
SyntaxError: /home/ubuntu/napa_rails/lib/napa/grape_extensions/grape_helpers.rb:3: syntax error, unexpected tLABEL
    def represent(data, with: nil, **args)
                             ^
/home/ubuntu/napa_rails/lib/napa/grape_extensions/grape_helpers.rb:3: Can't assign to nil
    def represent(data, with: nil, **args)
                                  ^
/home/ubuntu/napa_rails/lib/napa/grape_extensions/grape_helpers.rb:22: syntax error, unexpected tLABEL
    def paginate(data, with: nil, **args)
                            ^
/home/ubuntu/napa_rails/lib/napa/grape_extensions/grape_helpers.rb:22: Can't assign to nil
    def paginate(data, with: nil, **args)
                                 ^
/home/ubuntu/napa_rails/lib/napa/grape_extensions/grape_helpers.rb:64: syntax error, unexpected keyword_end, expecting $end
```

**Comment by jonhoman** [comment]
Fixed. Ruby version issue.

**Comment by fgv02009** [comment]
I'm ok with this. Can you update the version of the gem? Maybe in the CHANGELOG and version.rb

**Comment by jonhoman** [comment]
@fgv02009 good call. Updating.

**Pull request merged**
